LLM data analysis docs
predictionguard/docs pull request #13
Opened 2023-12-05 14:51 UTC by sharanshirodkar7

2023-12-06 17:03 UTC, dwhitena requested changes

2023-12-06 17:03 UTC, dwhitena commented on pages/guides/ada.md
> +conn = duckdb.connect()
I think this can be a bit more simple. I did this:

```python
def execute_sql(query):
  df = duckdb.sql(query).df()
  return df
```

2023-12-06 17:03 UTC, dwhitena commented on pages/guides/ada.md
> +# A demo of our PG query generator in action
Maybe a more formatted screenshot of the dataframe in the Jupyter notebook or a GIF showing the query in motion?

2023-12-06 17:03 UTC, dwhitena commented on pages/guides/ada.md
> +
Is there a Colab notebook we could link to? Maybe similar to here: https://docs.predictionguard.com/usingllms/accessing

2023-12-06 17:15 UTC, sharanshirodkar7 commented on pages/guides/ada.md
> +title: Code Generator
yes that sounds great and short too

2023-12-06 17:23 UTC, sharanshirodkar7 commented on pages/guides/ada.md
> +Large language models (LLMs) like Nous-Hermer-Llama2, WizardCoder have shown impressive capabilities for understanding and generating natural language. We can leverage these skills for data analysis
Understood...makes sense.

2023-12-14 15:58 UTC, dwhitena approved these changes

2023-12-14 15:58 UTC, merged